version: "3.8"

networks:
  ghost-network:
    driver: overlay

services:
  ghost:
    image: node:lts
    working_dir: /var/lib/ghost
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - target: 9229
        published: 9235
        protocol: tcp
        mode: ingress
      - target: 2368
        published: 2368
        protocol: tcp
        mode: ingress
      - target: 4200
        published: 4200
        protocol: tcp
        mode: ingress
    networks:
      - ghost-network
    environment:
      PATH: /var/lib/ghost/node_modules/.bin:${PATH}
      url: ${URL}
      admin__url: ${ADMIN_URL}
      server__host: 0.0.0.0
      NODE_ENV: development
      mail__transport: SMTP
      mail__options__host: mailhog
      mail__options__port: 1025
      database__client: sqlite3
    deploy:
      replicas: 1
    volumes:
      - .:/var/lib/ghost
    entrypoint:
      ["grunt", "dev"]
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - ghost-network
    deploy:
      replicas: 1