name: Docker Image CI

on:
  workflow_dispatch:
    
  create:
    tags: releases/[1-9]+.[0-9]+.[0-9]+-[0-9]+
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
      - name: Set tag using ref.
        if: startsWith( github.ref, 'refs/tags/releases/')
        run: |
          [[ ${{ github.ref }} =~ releases/([1-9]+.[0-9]+.[0-9]+-[0-9]+) ]]
          echo "tag=ghcr.io/june07/ghost/ghost-largesse:${BASH_REMATCH[1]}" >> $GITHUB_ENV
          
      - name: Set tag using date string.
        if: "! startsWith( github.ref, 'refs/tags/releases/')"
        run: |
          echo "tag=ghcr.io/june07/ghost/ghost-largesse:$(date +%s)" >> $GITHUB_ENV
      
      - name: test
        run: echo ${{ env.tag }}
          
# until https://github.com/actions/download-artifact/issues/3 is resolved, the build process must be repeated
#      - name: Download release files
#        uses: actions/download-artifact@v2
#        with:
#          name: ghost-latest

      - name: Checkout
        uses: actions/checkout@v2        
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.0'

      - run: yarn
      - run: grunt release --skip-tests

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.tag }}
      
      - name: Push to GitHub Packages
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
          docker push ${{ env.tag }}
          
      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          ssh ${{ secrets.SSH_HOST }} -l ${{ secrets.SSH_USER }} "~/6fb10e01-779b-4c8d-898b-9779a61d6856/ghost/update.sh ${{ env.tag }}" 
          
