name: Docker Image CI

on:
  push:
    branches:
      - master

  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          echo "tag=ghost-largesse:$(date +%s)" >> $GITHUB_ENV
      
      - name: test
        run: echo ${{ env.tag }}
          
# until https://github.com/actions/download-artifact/issues/3 is resolved, the build process must be repeated
#      - name: Download release files
#        uses: actions/download-artifact@v2
#        with:
#          name: ghost-latest

      - name: Checkout
        uses: actions/checkout@v2        
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.0'

      - run: yarn
      - run: grunt release --skip-tests

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.tag }}
      
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: june07/ghost/${{ env.tag }}
          tag_with_ref: true
